# Shadowrocket: 2026-01-23 10:53:15
[General]
update-url = https://raw.githubusercontent.com/kuciybes/shadowrocket/main/lteconf.conf
proxylist = url-test, policy-path=subscription

[Rule]
#ru direct
DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,рф,DIRECT

#google (youtube, ai, play store)
DOMAIN-KEYWORD,app-analytics-services,LTEEU
DOMAIN-KEYWORD,play.googleapis,LTEEU
DOMAIN-KEYWORD,oauth,LTEEU
DOMAIN-KEYWORD,ai.google,LTEEU
DOMAIN-KEYWORD,developerprofiles-pa,LTEEU
DOMAIN-KEYWORD,notebooklm,LTEEU
DOMAIN-KEYWORD,gemini,LTEEU
DOMAIN-KEYWORD,aistudio,LTEEU
DOMAIN-KEYWORD,generativelanguage,LTEEU
DOMAIN-KEYWORD,google.ai,LTEEU
DOMAIN-KEYWORD,ai.google,LTEEU
DOMAIN-KEYWORD,google.dev,LTEEU
DOMAIN-KEYWORD,play.google.com,LTEEU
DOMAIN-KEYWORD,clients6,LTEEU
DOMAIN-KEYWORD,googleapis,RU
DOMAIN-KEYWORD,ytimg,RU
DOMAIN-KEYWORD,googlevideo,RU
DOMAIN-KEYWORD,ggpht,RU
DOMAIN-KEYWORD,gstatic,RU
DOMAIN-KEYWORD,youtube-nocookie,RU
DOMAIN-KEYWORD,googleusercontent,RU
DOMAIN-KEYWORD,youtu,RU

#ru
#DOMAIN-SUFFIX,ru,RU
#DOMAIN-SUFFIX,рф,RU

#ai
DOMAIN-KEYWORD,openai,LTEEU
DOMAIN-KEYWORD,oai,LTEEU
DOMAIN-KEYWORD,gpt,LTEEU
DOMAIN-KEYWORD,anthropic,LTEEU
DOMAIN-KEYWORD,claude,LTEEU
DOMAIN-KEYWORD,openrouter,LTEEU
DOMAIN-KEYWORD,deepl,LTEEU
DOMAIN-KEYWORD,models.dev,LTEEU
DOMAIN-KEYWORD,influxdata,LTEEU

#twitter/x
DOMAIN-KEYWORD,twimg,LTEEU
DOMAIN-KEYWORD,twitter,LTEEU
DOMAIN-KEYWORD,x.com,LTEEU
DOMAIN-KEYWORD,twtrdns,LTEEU
DOMAIN-KEYWORD,twttr,LTEEU

#steam
DOMAIN-KEYWORD,steam,LTEEU

#linkedin
DOMAIN-KEYWORD,linkedin,LTEEU
DOMAIN-KEYWORD,licdn,LTEEU

#spotify
DOMAIN-KEYWORD,spotify,LTEEU
DOMAIN-KEYWORD,scdn,LTEEU

#notion
DOMAIN-KEYWORD,notion,LTEEU

#medium
DOMAIN-KEYWORD,medium.com,LTEEU

#twitch
DOMAIN-KEYWORD,twitch,LTEEU
DOMAIN-KEYWORD,ttvnw,LTEEU
DOMAIN-KEYWORD,jtvnw,LTEEU

#fb/insta/meta
DOMAIN-KEYWORD,facebook,LTERU
DOMAIN-KEYWORD,fbcdn,LTERU
DOMAIN-KEYWORD,fbpigeon,LTERU
DOMAIN-KEYWORD,fbsbx,LTERU
DOMAIN-KEYWORD,m.me,LTERU
DOMAIN-KEYWORD,meta,LTERU
DOMAIN-KEYWORD,insta,LTERU
DOMAIN-KEYWORD,igcdn,LTERU
DOMAIN-KEYWORD,igsonar,LTERU
DOMAIN-KEYWORD,igtv,LTERU
DOMAIN-KEYWORD,whatsapp,LTERU
DOMAIN-KEYWORD,wa.me,LTERU

#dev
DOMAIN-KEYWORD,github,LTEEU
DOMAIN-KEYWORD,vscode,LTEEU
DOMAIN-KEYWORD,n8n,LTEEU
DOMAIN-KEYWORD,greasyfork,LTEEU
DOMAIN-KEYWORD,adspower,LTEEU

#shopping
DOMAIN-KEYWORD,amazon,LTEEU
DOMAIN-KEYWORD,iherb,LTEEU

#media
DOMAIN-KEYWORD,canva,LTEEU
DOMAIN-KEYWORD,discord,LTEEU
DOMAIN-KEYWORD,patreon,LTEEU

#books
DOMAIN-KEYWORD,flibusta,LTEEU
DOMAIN-KEYWORD,goodreads,LTERU
DOMAIN-KEYWORD,gr-assets,LTEEU

#misc
DOMAIN-KEYWORD,myheritage,LTEEU
DOMAIN-KEYWORD,paddle,LTEEU
DOMAIN-KEYWORD,slivup,LTEEU
DOMAIN-KEYWORD,sharewood,LTEEU
DOMAIN-KEYWORD,blizzard,LTEEU
DOMAIN-KEYWORD,blz-content,LTEEU
DOMAIN-KEYWORD,sms,LTEEU

#adult
DOMAIN-KEYWORD,phncdn,LTEEU
DOMAIN-KEYWORD,pornhub,LTEEU
DOMAIN-KEYWORD,xvideos,LTEEU
DOMAIN-KEYWORD,xv-ru,LTEEU
DOMAIN-KEYWORD,cdn77,LTEEU

#torrents
DOMAIN-KEYWORD,rutracker,LTERU
DOMAIN-KEYWORD,rutor,LTERU
DOMAIN-KEYWORD,nnm,LTERU

#FINAL
FINAL,DIRECT
